# Site settings
title: "东方未明"
#description: 
#代云陇雁浙江潮，人有迷魂犹待招。
#世间多少金谷客，数声鹤唳念遥遥。
baseurl: ""
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://east-before-dawn.github.io"


# GitHub User settings
username: Username
github_username: "east-before-dawn"
user_description: user_description
user_title: user_title
email:
repository: east-before-dawn/east-before-dawn.github.io

# Blog Author settings
author:
  name: 东方未明
  picture:
  email:
  description:
  twitter:
  facebook:
  github:
  linkedin:
  clustrmap:

#全局设置
encoding: utf-8
timezone: Asia/Hong_Kong

# baidu 统计

# markdown
markdown: kramdown

kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1

highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Front Matter 默认值
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"


